### ISSUE TITLE
ialu.de checklist

### ISSUE THREAD

**Issue by christianparpart** [christianparpart/ialu-todo#1]
* [ ] passwort vergessen link
* [ ] VIPs zu admins machen, oder VIPs group-admin rechte geben
* [ ] VIPs: gb entries loeschen koennen (jegliche)
* [ ] caelum: immernoch admin? (fragen)
* [ ] http://ialu.de/forums/4/posts/1090
* [ ] Feature: Userpages must not be visible to SEO nor guests. You must be logged in. -- ggf fuer jeden user als flag aktivierbar/deaktivierbar machen.
* [ ] chat /quit command should not spam web output

**Comment by RudeDolph** [comment]
* Logs werden sporadisch nicht versendet (betreffen alle Log-Arten: Autologs, gestartete Logs und Lastlogs)

**Comment by RudeDolph** [comment]
- Autologlisten können über den Befehl /autolog nicht bearbeitet werden. Der Befehl wirft eine Bestätigung aus, es wird jedoch nichts geändert.

**Comment by RudeDolph** [comment]
- Gruppenbanner kann nicht hochgeladen werden. Fehlermeldung: 

"2 errors prohibited this group from being saved:    
Banner Could not run the `identify` command.  Please install ImageMagick.    
Banner Could not run the `identify` command. Please install ImageMagick."

**Comment by RudeDolph** [comment]
Wir werden häufig angesprochen, dass ungenutzte Nicknames nicht (wie in den ANB angegeben) nach 6 Monaten gelöscht werden. Sollte das nicht automatisch passieren wie im Ninchens damals?

Es existieren viele Accounts, die schon lange nicht mehr genutzt werden und damit Nicknames blockieren. Ist es möglich, dass ungenutzte Nicknames wieder automatisch gelöscht werden und Hauptnicknames bestehen bleiben, damit Account bleibt?

Hat dies auch eine positive Auswirkung auf die Serverlast, wenn hier aufgeräumt wird?
